# Generated by Django 5.2.5 on 2025-08-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(default='natural', max_length=20)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('razon_social', models.TextField(blank=True, null=True)),
                ('nombre_comercial', models.TextField(blank=True, null=True)),
                ('giro', models.TextField(blank=True, null=True)),
                ('dui', models.TextField(blank=True, null=True)),
                ('nit', models.TextField(blank=True, null=True, unique=True)),
                ('nrc', models.TextField(blank=True, null=True, unique=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('direccion_fiscal', models.TextField(blank=True, null=True)),
                ('departamento', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('telefono_facturacion', models.TextField(blank=True, null=True)),
                ('email_facturacion', models.TextField(blank=True, null=True)),
                ('contacto', models.TextField(blank=True, null=True)),
                ('contribuyente_iva', models.BooleanField(db_index=True, default=False)),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_deuda', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='api.clientes')),
            ],
            options={
                'db_table': 'creditos',
            },
        ),
        migrations.CreateModel(
            name='PagosCredito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('credito', models.ForeignKey(db_column='credito_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.creditos')),
            ],
            options={
                'db_table': 'pagos_credito',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('nombre', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('condicion', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('estado_usado', models.CharField(blank=True, choices=[('como_nuevo', 'Como nuevo'), ('muy_bueno', 'Muy bueno'), ('bueno', 'Bueno (detalle leve)')], db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='api.categorias')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_venta', models.DateTimeField()),
                ('producto_codigo_snapshot', models.TextField(blank=True, null=True)),
                ('producto_nombre_snapshot', models.TextField(blank=True, null=True)),
                ('producto_costo_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('producto_condicion_snapshot', models.TextField(blank=True, null=True)),
                ('producto_categoria_id_snapshot', models.BigIntegerField(blank=True, null=True)),
                ('producto_categoria_nombre_snapshot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='api.productos')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('documento_tipo', models.CharField(default='ticket', max_length=30)),
                ('documento_serie', models.TextField(blank=True, null=True)),
                ('documento_numero', models.TextField(blank=True, null=True)),
                ('iva_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cliente', models.ForeignKey(db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clientes')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('producto_codigo_snapshot', models.TextField(blank=True, null=True)),
                ('producto_nombre_snapshot', models.TextField(blank=True, null=True)),
                ('producto_costo_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('producto_condicion_snapshot', models.TextField(blank=True, null=True)),
                ('producto_categoria_id_snapshot', models.BigIntegerField(blank=True, null=True)),
                ('producto_categoria_nombre_snapshot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('detalle_venta', models.ForeignKey(db_column='detalle_venta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.detalleventa')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='api.productos')),
                ('venta', models.ForeignKey(db_column='venta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ventas')),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.ventas'),
        ),
        migrations.CreateModel(
            name='CreditosHistorialCompras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('credito', models.ForeignKey(db_column='credito_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.creditos')),
                ('venta', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, to='api.ventas')),
            ],
            options={
                'db_table': 'creditos_historial_compras',
            },
        ),
    ]
