# Generated by Django 5.2.5 on 2025-08-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="override",
            field=models.BooleanField(default=False),
        ),
    ]
