# Generated by Django 5.2.5 on 2025-08-30 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_ventas_fecha_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("gerente", "Gerente"),
                            ("vendedor", "Vendedor"),
                        ],
                        db_index=True,
                        default="vendedor",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
