# Generated by Django 5.2.5 on 2025-08-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_seed_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="producto",
            field=models.ForeignKey(
                db_column="producto_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.productos",
            ),
        ),
        migrations.AlterField(
            model_name="devoluciones",
            name="producto",
            field=models.ForeignKey(
                db_column="producto_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.productos",
            ),
        ),
    ]
