# Generated by Django 5.2.6 on 2025-09-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_productos_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="devuelto",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="devoluciones",
            name="ingreso_afectado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddIndex(
            model_name="clientes",
            index=models.Index(fields=["nombre"], name="clientes_nombre_idx"),
        ),
        migrations.AddIndex(
            model_name="detalleventa",
            index=models.Index(
                fields=["venta", "producto", "producto_codigo_snapshot"],
                name="detalleventa_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ventas",
            index=models.Index(
                fields=["created_at", "estado", "cliente"], name="ventas_cre_cli_idx"
            ),
        ),
    ]
