# Generated by Django 6.0 on 2025-12-25 17:48

from django.db import migrations, models


def drop_dependencies(apps, schema_editor):
    """Eliminar vistas y triggers que dependen de las columnas a eliminar"""
    with schema_editor.connection.cursor() as cursor:
        # Eliminar vistas
        cursor.execute("DROP VIEW IF EXISTS productos_activos CASCADE;")
        cursor.execute("DROP VIEW IF EXISTS productos_archivados CASCADE;")
        # Eliminar trigger que depende de stock
        cursor.execute("DROP TRIGGER IF EXISTS trg_archive_used_when_zero ON productos CASCADE;")


def reverse_drop_dependencies(apps, schema_editor):
    """Recrear vistas (solo para rollback) - trigger no se recrea"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE OR REPLACE VIEW productos_activos AS 
            SELECT * FROM productos WHERE status='active';
        """)
        cursor.execute("""
            CREATE OR REPLACE VIEW productos_archivados AS 
            SELECT * FROM productos WHERE status='archived';
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_productos_codigo_alter_usuario_id'),
    ]

    operations = [
        migrations.RunPython(drop_dependencies, reverse_drop_dependencies),
        migrations.RemoveField(
            model_name='productos',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='estado_usado',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], db_index=True, default='producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
